# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\wang\Desktop\hiero_shot.ui'
#
# Created: Mon Jun 12 18:04:09 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!
import os
import sys
from PySide import QtCore, QtGui
G_base_path = unicode(os.path.dirname(os.path.dirname( sys.argv[0] ))).replace("\\","/")
G_Icon_path = G_base_path + "/com_icon/"
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 720)
        Form.setMinimumSize(QtCore.QSize(1080, 720))
        Form.setMaximumSize(QtCore.QSize(1080, 720))
        Form.setStyleSheet("background:rgb(45,53,61);")
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_lay = QtGui.QHBoxLayout()
        self.main_lay.setSpacing(0)
        self.main_lay.setContentsMargins(8, 8, 8, 8)
        self.main_lay.setObjectName("main_lay")
        self.button_Icon = QtGui.QPushButton(Form)
        self.button_Icon.setMinimumSize(QtCore.QSize(25, 25))
        self.button_Icon.setStyleSheet("background-color:rgb(45,53,61);border:1px solid rgb(45,53,61);")
        self.button_Icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap( G_Icon_path + "logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_Icon.setIcon(icon)
        self.button_Icon.setIconSize(QtCore.QSize(25, 25))
        self.button_Icon.setObjectName("button_Icon")
        self.main_lay.addWidget(self.button_Icon)
        spacerItem = QtGui.QSpacerItem(40, 25, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.main_lay.addItem(spacerItem)
        self.button_minwindows = QtGui.QPushButton(Form)
        self.button_minwindows.setMinimumSize(QtCore.QSize(25, 25))
        self.button_minwindows.setStyleSheet("background-color:rgb(45,53,61);border:1px solid rgb(45,53,61);")
        self.button_minwindows.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(G_Icon_path + "min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_minwindows.setIcon(icon1)
        self.button_minwindows.setIconSize(QtCore.QSize(25, 25))
        self.button_minwindows.setObjectName("button_minwindows")
        self.main_lay.addWidget(self.button_minwindows)
        self.button_close = QtGui.QPushButton(Form)
        self.button_close.setMinimumSize(QtCore.QSize(25, 25))
        self.button_close.setStyleSheet("background-color:rgb(45,53,61);border:1px solid rgb(45,53,61);")
        self.button_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap( G_Icon_path + "close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_close.setIcon(icon2)
        self.button_close.setIconSize(QtCore.QSize(25, 25))
        self.button_close.setObjectName("button_close")
        self.main_lay.addWidget(self.button_close)
        self.verticalLayout.addLayout(self.main_lay)
        self.stackwidget = QtGui.QStackedWidget(Form)
        self.stackwidget.setObjectName("stackwidget")
        self.page_1 = QtGui.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page_1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtGui.QFrame(self.page_1)
        self.frame.setStyleSheet("border:2px solid rgb(59,66,73);background-color:rgb(50,59,68);")
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem1 = QtGui.QSpacerItem(150, 80, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setContentsMargins(0, 20, 0, 20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_project = QtGui.QLabel(self.frame)
        self.label_project.setMinimumSize(QtCore.QSize(120, 40))
        self.label_project.setMaximumSize(QtCore.QSize(120, 40))
        self.label_project.setStyleSheet("border:0px solid rgb(59,175,218);font-size:18px;color:rgb(126,132,138);font-family : \'微软雅黑\';")
        self.label_project.setObjectName("label_project")
        self.horizontalLayout_4.addWidget(self.label_project)
        self.combobox_project = QtGui.QComboBox(self.frame)
        self.combobox_project.setMinimumSize(QtCore.QSize(250, 40))
        self.combobox_project.setMaximumSize(QtCore.QSize(250, 40))
        self.combobox_project.setObjectName("combobox_project")
        self.horizontalLayout_4.addWidget(self.combobox_project)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(0, 20, 0, 20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(120, 40))
        self.label_2.setMaximumSize(QtCore.QSize(120, 40))
        self.label_2.setStyleSheet("border:0px solid rgb(59,175,218);font-size:18px;color:rgb(126,132,138);font-family : \'微软雅黑\';")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.combobox_eps = QtGui.QComboBox(self.frame)
        self.combobox_eps.setMinimumSize(QtCore.QSize(250, 40))
        self.combobox_eps.setMaximumSize(QtCore.QSize(250, 40))
        self.combobox_eps.setObjectName("combobox_eps")
        self.horizontalLayout_3.addWidget(self.combobox_eps)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setContentsMargins(0, 20, 0, 20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.label_format = QtGui.QLabel(self.frame)
        self.label_format.setMinimumSize(QtCore.QSize(120, 40))
        self.label_format.setMaximumSize(QtCore.QSize(120, 40))
        self.label_format.setStyleSheet("border:0px solid rgb(59,175,218);font-size:18px;color:rgb(126,132,138);font-family : \'微软雅黑\';")
        self.label_format.setObjectName("label_format")
        self.horizontalLayout_5.addWidget(self.label_format)
        self.combobox_format = QtGui.QComboBox(self.frame)
        self.combobox_format.setMinimumSize(QtCore.QSize(250, 40))
        self.combobox_format.setMaximumSize(QtCore.QSize(250, 40))
        self.combobox_format.setObjectName("combobox_format")
        self.horizontalLayout_5.addWidget(self.combobox_format)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setContentsMargins(0, 20, 0, 20)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setMinimumSize(QtCore.QSize(120, 40))
        self.label_4.setMaximumSize(QtCore.QSize(120, 40))
        self.label_4.setStyleSheet("border:0px solid rgb(59,175,218);font-size:18px;color:rgb(126,132,138);font-family : \'微软雅黑\';")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.lineEdit = QtGui.QLineEdit(self.frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(208, 40))
        self.lineEdit.setMaximumSize(QtCore.QSize(208, 40))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.pushButton = QtGui.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(42, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(42, 40))
        self.pushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap( G_Icon_path + "down_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setIconSize(QtCore.QSize(42, 40))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10)
        self.verticalLayout_2.addWidget(self.frame)
        self.progressBar = QtGui.QProgressBar(self.page_1)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 10))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.stackwidget.addWidget(self.page_1)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtGui.QFrame(self.page_2)
        self.frame_2.setStyleSheet("border:1px solid rgb(59,66,73);background-color:rgb(50,59,68);")
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tablewidget = QtGui.QTableWidget(self.frame_2)
        self.tablewidget.setObjectName("tablewidget")
        self.tablewidget.setColumnCount(9)
        self.tablewidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setHorizontalHeaderItem(8, item)
        self.tablewidget.horizontalHeader().setVisible(True)
        self.tablewidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tablewidget.horizontalHeader().setHighlightSections(True)
        self.tablewidget.horizontalHeader().setSortIndicatorShown(False)
        self.tablewidget.horizontalHeader().setStretchLastSection(False)
        self.tablewidget.verticalHeader().setVisible(True)
        self.tablewidget.verticalHeader().setCascadingSectionResizes(False)
        self.tablewidget.verticalHeader().setHighlightSections(True)
        self.tablewidget.verticalHeader().setSortIndicatorShown(False)
        self.tablewidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_6.addWidget(self.tablewidget)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.stackwidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtGui.QFrame(self.page_3)
        self.frame_3.setStyleSheet("border:1px solid rgb(59,66,73);background-color:rgb(50,59,68);")
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.progressBar_input = QtGui.QProgressBar(self.frame_3)
        self.progressBar_input.setProperty("value", 24)
        self.progressBar_input.setTextVisible(False)
        self.progressBar_input.setObjectName("progressBar_input")
        self.verticalLayout_7.addWidget(self.progressBar_input)
        self.textEdit_input = QtGui.QTextEdit(self.frame_3)
        self.textEdit_input.setStyleSheet("border: 1px solid rgb(90,100,110);border-radius:6px;font-size:16px;color:rgb(126,132,138);font-family : \'微软雅黑\';")
        self.textEdit_input.setObjectName("textEdit_input")
        self.verticalLayout_7.addWidget(self.textEdit_input)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.stackwidget.addWidget(self.page_3)
        self.verticalLayout.addWidget(self.stackwidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_rename = QtGui.QPushButton(Form)
        self.button_rename.setMinimumSize(QtCore.QSize(160, 30))
        self.button_rename.setMaximumSize(QtCore.QSize(160, 30))
        self.button_rename.setStyleSheet("background-color:rgb(76,86,103);border:1px solid rgb(76,86,103); border-radius:6px;font-size:18px;color:rgb(255,255,255);font-family : \'微软雅黑\';")
        self.button_rename.setObjectName("button_rename")
        self.horizontalLayout_2.addWidget(self.button_rename)
        self.button_dlt = QtGui.QPushButton(Form)
        self.button_dlt.setMinimumSize(QtCore.QSize(80, 30))
        self.button_dlt.setMaximumSize(QtCore.QSize(80, 30))
        self.button_dlt.setStyleSheet("background-color:rgb(76,86,103);border:1px solid rgb(76,86,103); border-radius:6px;font-size:18px;color:rgb(255,255,255);font-family : \'微软雅黑\';")
        self.button_dlt.setObjectName("button_dlt")
        self.horizontalLayout_2.addWidget(self.button_dlt)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.button_last = QtGui.QPushButton(Form)
        self.button_last.setMinimumSize(QtCore.QSize(80, 30))
        self.button_last.setMaximumSize(QtCore.QSize(80, 30))
        self.button_last.setStyleSheet("background-color:rgb(76,86,103);border:1px solid rgb(76,86,103); border-radius:6px;font-size:18px;color:rgb(255,255,255);font-family : \'微软雅黑\';")
        self.button_last.setObjectName("button_last")
        self.horizontalLayout_2.addWidget(self.button_last)
        self.button_next = QtGui.QPushButton(Form)
        self.button_next.setMinimumSize(QtCore.QSize(80, 30))
        self.button_next.setMaximumSize(QtCore.QSize(80, 30))
        self.button_next.setStyleSheet("background-color:rgb(59,175,218);border:1px solid rgb(59,175,218); border-radius:6px;font-size:18px;color:rgb(255,255,255);font-family : \'微软雅黑\';")
        self.button_next.setObjectName("button_next")
        self.horizontalLayout_2.addWidget(self.button_next)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        self.stackwidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_project.setText(QtGui.QApplication.translate("Form", "      项目:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "      集数:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_format.setText(QtGui.QApplication.translate("Form", "      格式:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "输出路径:", None, QtGui.QApplication.UnicodeUTF8))
        self.tablewidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "镜头号", None, QtGui.QApplication.UnicodeUTF8))
        self.tablewidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "帧数", None, QtGui.QApplication.UnicodeUTF8))
        self.tablewidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "状态", None, QtGui.QApplication.UnicodeUTF8))
        self.tablewidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "开始帧缩略图", None, QtGui.QApplication.UnicodeUTF8))
        self.tablewidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "结束帧缩略图", None, QtGui.QApplication.UnicodeUTF8))
        self.tablewidget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Form", "开始时间码", None, QtGui.QApplication.UnicodeUTF8))
        self.tablewidget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Form", "结束时间码", None, QtGui.QApplication.UnicodeUTF8))
        self.tablewidget.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("Form", "卷号", None, QtGui.QApplication.UnicodeUTF8))
        self.tablewidget.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("Form", "素材名", None, QtGui.QApplication.UnicodeUTF8))
        self.button_rename.setText(QtGui.QApplication.translate("Form", "重命名镜头号", None, QtGui.QApplication.UnicodeUTF8))
        self.button_dlt.setText(QtGui.QApplication.translate("Form", "删除", None, QtGui.QApplication.UnicodeUTF8))
        self.button_last.setText(QtGui.QApplication.translate("Form", "上一步", None, QtGui.QApplication.UnicodeUTF8))
        self.button_next.setText(QtGui.QApplication.translate("Form", "下一步", None, QtGui.QApplication.UnicodeUTF8))

